#!/usr/bin/env python3
"""Fan out the canonical agent assets (agents/) to per-tool locations.

Canonical sources (EDIT THESE, never the generated copies):
    agents/skills/<name>/SKILL.md (+ references/)   portable Agent Skills
    agents/subagents/<name>.md                      subagent definitions

Generated targets:
    .claude/skills/<name>/      Claude Code skills
    .claude/agents/<name>.md    Claude Code subagents
    .opencode/skill/<name>/     OpenCode skills
    .opencode/agent/<name>.md   OpenCode agents (mode: subagent)
    .codex/skills/<name>/       Codex skills
    .cursor/rules/foamagent-skills.mdc   Cursor pointer rule

Every deployed skill also gets the subagent definitions copied into
references/subagents/ so harnesses without native subagents can follow them
inline.

Usage:
    python scripts/sync_agent_assets.py           # regenerate all targets
    python scripts/sync_agent_assets.py --check   # exit 1 if targets are stale (CI)
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS_SRC = REPO / "agents" / "skills"
SUBAGENTS_SRC = REPO / "agents" / "subagents"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/sync_agent_assets.py from {source} — "
    "edit the source and re-run the script; do not edit this copy. -->"
)

# Tool targets for skill directories (dir-copy of SKILL.md + references/).
# .cursor/skills renders identically to the others; the .cursor pointer rule
# (CURSOR_RULE_PATH) is handled separately.
SKILL_DIR_TARGETS = [
    ".claude/skills",
    ".opencode/skill",
    ".codex/skills",
    ".cursor/skills",
]

# Tool targets for subagent markdown files: (target dir, extra frontmatter lines)
SUBAGENT_TARGETS = [
    (".claude/agents", []),
    (".opencode/agent", ["mode: subagent"]),
]

CURSOR_RULE_PATH = ".cursor/rules/foamagent-skills.mdc"


def _discover_skills() -> list[Path]:
    """Every skill source directory (those containing a SKILL.md), sorted."""
    return [d for d in sorted(SKILLS_SRC.iterdir()) if (d / "SKILL.md").is_file()]


def _frontmatter_end(lines: list[str]) -> int | None:
    """Index of the closing '---' of a leading YAML frontmatter block, else None."""
    if not (lines and lines[0].strip() == "---"):
        return None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return i
    return None


def _with_note(content: str, source: Path) -> str:
    """Insert the GENERATED note right after the frontmatter block."""
    note = GENERATED_NOTE.format(source=source.relative_to(REPO).as_posix())
    lines = content.split("\n")
    end = _frontmatter_end(lines)
    if end is not None:
        return "\n".join(lines[: end + 1] + ["", note] + lines[end + 1:])
    return note + "\n\n" + content


def _add_frontmatter_keys(content: str, extra: list[str]) -> str:
    if not extra:
        return content
    lines = content.split("\n")
    end = _frontmatter_end(lines)
    if end is not None:
        return "\n".join(lines[:end] + extra + lines[end:])
    return content


def _build_skill_dir(skill_dir: Path, out_dir: Path) -> None:
    """Render one skill directory (with note + bundled subagents) into out_dir."""
    for src in sorted(skill_dir.rglob("*")):
        if not src.is_file():
            continue
        rel = src.relative_to(skill_dir)
        dst = out_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src.suffix == ".md":
            dst.write_text(_with_note(src.read_text(encoding="utf-8"), src), encoding="utf-8")
        else:
            shutil.copy2(src, dst)

    # Bundle subagents so subagent-less harnesses can follow them inline
    if SUBAGENTS_SRC.exists():
        for sub in sorted(SUBAGENTS_SRC.glob("*.md")):
            dst = out_dir / "references" / "subagents" / sub.name
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_text(_with_note(sub.read_text(encoding="utf-8"), sub), encoding="utf-8")


def _build_cursor_rule() -> str:
    skills = [d.name for d in _discover_skills()]
    skill_lines = "\n".join(
        f"- `{name}`: read and follow `.cursor/skills/{name}/SKILL.md`" for name in skills
    )
    body = f"""---
description: OpenFOAM CFD simulation workflows via the foamagent MCP server (Foam-Agent skills)
alwaysApply: false
---

{GENERATED_NOTE.format(source='agents/skills')}

When the user asks to set up, run, debug or visualize an OpenFOAM CFD
simulation, use the matching Foam-Agent skill:

{skill_lines}

These skills orchestrate the `foamagent` MCP tools (tutorial retrieval, case
file I/O, simulation execution). Follow the referenced SKILL.md step by step;
subagent roles are bundled under its references/subagents/ directory — follow
them inline.
"""
    return body


def _render_all(root: Path) -> None:
    """Render every generated asset under the given root (repo or temp dir)."""
    skills = _discover_skills()

    for target in SKILL_DIR_TARGETS:
        for skill in skills:
            _build_skill_dir(skill, root / target / skill.name)

    if SUBAGENTS_SRC.exists():
        for target_dir, extra in SUBAGENT_TARGETS:
            for sub in sorted(SUBAGENTS_SRC.glob("*.md")):
                content = _with_note(sub.read_text(encoding="utf-8"), sub)
                content = _add_frontmatter_keys(content, extra)
                dst = root / target_dir / sub.name
                dst.parent.mkdir(parents=True, exist_ok=True)
                dst.write_text(content, encoding="utf-8")

    rule = root / CURSOR_RULE_PATH
    rule.parent.mkdir(parents=True, exist_ok=True)
    rule.write_text(_build_cursor_rule(), encoding="utf-8")


def _managed_paths(root: Path) -> list[Path]:
    """Every path this script owns (for cleaning and for --check)."""
    paths = []
    skills = [d.name for d in _discover_skills()]
    for target in SKILL_DIR_TARGETS:
        for name in skills:
            paths.append(root / target / name)
    if SUBAGENTS_SRC.exists():
        for target_dir, _ in SUBAGENT_TARGETS:
            for sub in sorted(SUBAGENTS_SRC.glob("*.md")):
                paths.append(root / target_dir / sub.name)
    paths.append(root / CURSOR_RULE_PATH)
    return paths


def _diff_trees(a: Path, b: Path) -> list[str]:
    """Return relative paths that differ between two rendered trees."""
    diffs = []
    a_files = {p.relative_to(a).as_posix() for p in a.rglob("*") if p.is_file()} if a.exists() else set()
    b_files = {p.relative_to(b).as_posix() for p in b.rglob("*") if p.is_file()} if b.exists() else set()
    for rel in sorted(a_files ^ b_files):
        diffs.append(rel)
    for rel in sorted(a_files & b_files):
        if not filecmp.cmp(a / rel, b / rel, shallow=False):
            diffs.append(rel)
    return diffs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify targets are up to date; exit 1 if stale")
    args = parser.parse_args()

    if not SKILLS_SRC.exists():
        print(f"No canonical skills found at {SKILLS_SRC}", file=sys.stderr)
        return 1

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_root = Path(tmp)
            _render_all(tmp_root)
            stale = []
            for expected in _managed_paths(tmp_root):
                actual = REPO / expected.relative_to(tmp_root)
                if expected.is_dir():
                    stale += [f"{actual.relative_to(REPO).as_posix()}/{d}" for d in _diff_trees(expected, actual)]
                elif expected.is_file():
                    if not actual.is_file() or not filecmp.cmp(expected, actual, shallow=False):
                        stale.append(actual.relative_to(REPO).as_posix())
            if stale:
                print("Stale generated agent assets (run: python scripts/sync_agent_assets.py):")
                for s in stale:
                    print(f"  {s}")
                return 1
            print("All generated agent assets are up to date.")
            return 0

    # Clean managed paths, then regenerate
    for path in _managed_paths(REPO):
        if path.is_dir():
            shutil.rmtree(path)
        elif path.is_file():
            path.unlink()
    _render_all(REPO)
    print("Agent assets synced to: " + ", ".join(
        SKILL_DIR_TARGETS + [".cursor/rules"] + [t for t, _ in SUBAGENT_TARGETS]
    ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
